// Generated by generate_data.py — do not edit; see data.json.
window.__NEWS__ = {
 "date": "Tuesday 8 September 2026",
 "generated_at": "23:57 UTC",
 "error": null,
 "total_stories": 77,
 "fx": {
  "pair": "EUR/MAD",
  "rate": 10.909,
  "change_pct": 0.0
 },
 "lanes": [
  {
   "key": "ai",
   "title": "AI & Models",
   "icon": "🤖",
   "note": null,
   "clusters": [
    {
     "label": "Llama · Cpp",
     "articles": [
      {
       "title": "Is RX 6800 + 6800 XT a sensible upgrade from 2x RTX 2060 OC 12GB for llama.cpp?",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wb3t30/is_rx_6800_6800_xt_a_sensible_upgrade_from_2x_rtx/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-08 22:47"
      },
      {
       "title": "How many agents can 2×4090 actually run at once? Three weeks of llama.cpp concurrency data — soft cap 5 @ 64k, hard cap 9, and why.",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wb35xo/how_many_agents_can_24090_actually_run_at_once/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-08 22:21"
      },
      {
       "title": "A hilarious comment about llama.cpp: “It’s a FB business using the pipeline to make profits”",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wazp0v/a_hilarious_comment_about_llamacpp_its_a_fb/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-08 20:13"
      },
      {
       "title": "Qwen3.8-Flash-Next in llama.cpp vs SGLang vs FreeToken: 35s vs 258s to first token at full context. My findings on new PRs coming to engines.",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1waydqj/qwen38flashnext_in_llamacpp_vs_sglang_vs/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-08 19:26"
      }
     ]
    },
    {
     "label": "Qwen · Gguf",
     "articles": [
      {
       "title": "Qwen 3.8 27b with PI agent - pushed to its 3D graphic game limits",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1waz5a0/qwen_38_27b_with_pi_agent_pushed_to_its_3d/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-08 19:53"
      },
      {
       "title": "DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NEO-CODER-MAX-MTP-GGUF · 353 ♥",
       "url": "https://huggingface.co/DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NEO-CODER-MAX-MTP-GGUF",
       "source": "HF new models",
       "published_at": "2026-09-01 07:01"
      },
      {
       "title": "ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF · 650 ♥",
       "url": "https://huggingface.co/ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF",
       "source": "HF new models",
       "published_at": "2026-08-28 18:38"
      }
     ]
    },
    {
     "label": "Muse · Agent",
     "articles": [
      {
       "title": "Muse: Meta's personal AI agent, features and capabilities",
       "url": "https://ai.meta.com/muse/",
       "source": "Hacker News",
       "published_at": "2026-09-08 19:25"
      },
      {
       "title": "Meta bets on AI agent Muse to catch up in AI race",
       "url": "https://www.theverge.com/ai-artificial-intelligence/991216/meta-bets-on-ai-agent-muse-to-catch-up-in-ai-race",
       "source": "Verge AI",
       "published_at": "2026-09-08 19:00"
      }
     ]
    },
    {
     "label": "Your",
     "articles": [
      {
       "title": "ChatGPT Sketch turns your bad drawings into detailed AI images",
       "url": "https://www.theverge.com/ai-artificial-intelligence/991727/openai-chatgpt-images-2-5-sketch",
       "source": "Verge AI",
       "published_at": "2026-09-08 20:16"
      },
      {
       "title": "I built Infercat: Share your local AI with friends over an encrypted p2p tunnel. Connect with an invite code from anywhere.",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1waxlpb/i_built_infercat_share_your_local_ai_with_friends/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-08 18:59"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "Drama swirls around OpenAI’s legendary mathematical milestone",
       "url": "https://www.theverge.com/ai-artificial-intelligence/991710/openai-navier-stokes-solution",
       "source": "Verge AI",
       "published_at": "2026-09-08 20:53"
      },
      {
       "title": "On the Value of Human Ideas: What data poisoning research reveals about \"autonomous\" AI breakthroughs",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wazzes/on_the_value_of_human_ideas_what_data_poisoning/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-08 20:23"
      },
      {
       "title": "Kimi K3 (2.8T) at 1 token/s on a MacBook Pro, streamed from four SSDs",
       "url": "https://github.com/argonautlabsai/deltafin",
       "source": "Hacker News",
       "published_at": "2026-09-08 20:07"
      },
      {
       "title": "openbmb/MiniCPM5-2B · 660 ♥",
       "url": "https://huggingface.co/openbmb/MiniCPM5-2B",
       "source": "HF new models",
       "published_at": "2026-09-06 11:12"
      },
      {
       "title": "OpenVDN/vdn-minimax-h3 · 246 ♥",
       "url": "https://huggingface.co/OpenVDN/vdn-minimax-h3",
       "source": "HF new models",
       "published_at": "2026-09-02 05:03"
      },
      {
       "title": "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp · 819 ♥",
       "url": "https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash-Vision-Exp",
       "source": "HF new models",
       "published_at": "2026-08-31 06:16"
      },
      {
       "title": "dealignai/GLM-5.3-CYBERSECURITY-FP8 · 313 ♥",
       "url": "https://huggingface.co/dealignai/GLM-5.3-CYBERSECURITY-FP8",
       "source": "HF new models",
       "published_at": "2026-08-30 10:46"
      }
     ]
    }
   ],
   "count": 18
  },
  {
   "key": "utoday",
   "title": "UTwente (UToday)",
   "icon": "📍",
   "note": null,
   "clusters": [
    {
     "label": "Moet",
     "articles": [
      {
       "title": "‘Ik weet niet zo goed wat ik hier moet doen’",
       "url": "https://news.google.com/rss/articles/CBMiggFBVV95cUxQWGlRLUNNVTdlb3ItVjVPb1NjVk9aN204SFNoZE52ZEZZdm0yU3A5NXJvUTY5UW5ma0xNNG1iS1IxeEh1UEJpVmRiaWVFYnlnZVhoLXdpUDdzN2x6TWcwaEFQSnY4WG5NTHNlT3l0UUJpQUxrM2NSTnBSRVQ1Ti12S3h3?oc=5",
       "source": "UToday",
       "published_at": "2026-08-19 14:47"
      },
      {
       "title": "Pakkerij moet per direct deuren sluiten na inspectie",
       "url": "https://news.google.com/rss/articles/CBMijgFBVV95cUxPcmppb3BwZ0tnV21aNTBCQm1EQzhudzZDeW1BUU5VZ0Y0NjlBUHFkUUNoNWNYeUtNWjZ3Zk9QbTF3VGZydTdBbUk0NzJtVFpONlVfLXZwbm9HNXhEX1p2WEFUTU1GeTQzVWtQcjdZWnJ3eUFjZVd6SFFSZWRBdVdweGNiRUFBcWIwZ3NtNUdn?oc=5",
       "source": "UToday",
       "published_at": "2026-05-21 07:00"
      }
     ]
    },
    {
     "label": "Bestuursfotoverkiezing · Grote",
     "articles": [
      {
       "title": "De Grote U-Today Bestuursfotoverkiezing 2026, de uitslag",
       "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxQNjU5OVlOSzctN0dKYlZ2ZVdzd2U1UWZCeEY0SXF3bzVfWTg0bXJqZGp0OGs2WUxSaGZlRVZLQjVSU2pZZGZXR1JsclBPZ1hFS1hQTVZmMXNxYTVOQ0w3NEJyS2xjZlhTWTlJQTl2LWV3bGdCaHQ2U1dLZldxeUxVVkpQYjA0LU1xY0VqMi1RU1RIM2RJVzdYdFd6UQ?oc=5",
       "source": "UToday",
       "published_at": "2026-06-25 07:00"
      },
      {
       "title": "Terug van (nooit) weggeweest: De Grote U-Today Bestuursfotoverkiezing",
       "url": "https://news.google.com/rss/articles/CBMioAFBVV95cUxNMUh5OFBxVGtqWTNXUG1kTUIxTFZSN0xwd0JWWXk4elRvdi1mZW4tYUxhU0VBOGRfQVA3bXpqaURjTUJjR1Ftb0M4QkZpQ01Mc2dZTTQzT29laXNENldKNzhOcFJ0NUtOYlNKT2dYNVYtWVRaZjU3SlAwQWs3R09TZjJaNHg5QjhuMmVPTlJjMEMzRmlXUm1Sd3luU0tGcWst?oc=5",
       "source": "UToday",
       "published_at": "2026-05-27 07:00"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "Opnieuw kwestie sociale onveiligheid op UT",
       "url": "https://news.google.com/rss/articles/CBMigAFBVV95cUxPWngwSE9iNzZ1OXhFMFBCaE12X25kbFRVY2U1YWlJWlZITzJTVXRnTm5QVGE2T2FaT2Zpek5VbTFXel9rTVRiSy1SQWtPa2RXSkotR2JRXzhhSEZPejRQblRDSjBiWjBkTE96Y1Y1WGlRYmhnWk53NWJrN0x4MG1ubg?oc=5",
       "source": "UToday",
       "published_at": "2026-08-31 06:00"
      },
      {
       "title": "Fraude met basisbeurs is te simpel: één vinkje levert honderden euro’s op",
       "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxPakRvSjdCMHpEU19hSEllZFFHLWJEanNVMGtrOHZMaVlfVjNGTThEZ0FkZEZpVHBnVGhUdDhxUjllbGFhWUhla0FJRFRsSzd4NHpYbzdOalpRY1QwY2dJYUFqUU1HUlpFUUxhT0FfQXI3TW5nRlZYNl9hNFZYOFE0cWxyck1SVzdNQUlrOXJKMUVSdUlSUk1DSWM5RERmRkxweUZzcUNINA?oc=5",
       "source": "UToday",
       "published_at": "2026-06-17 07:00"
      },
      {
       "title": "Elfbierentocht vs alcoholconvenant: ‘Cola mag ook’",
       "url": "https://news.google.com/rss/articles/CBMijAFBVV95cUxQRjNkNzM5VjZVV3ZEaC05UzRpVG9kLUZFQkc3Nzk3UDlqWXlPaFNzZFVieXBpbWlyTDRQcEFvNVVlRmJtX3BTTXNUZlctWGlQSzA1NXVER2NYcWJDaU1valZ1T3AxR0NsOWtHZmxpcHZvX1VJd0l5cFRqNGlSdG9mZDhEU2VyOG13bHAxZg?oc=5",
       "source": "UToday",
       "published_at": "2026-06-10 07:00"
      },
      {
       "title": "Vermoeidheid na borstkanker speelt veel vrouwen parten",
       "url": "https://news.google.com/rss/articles/CBMikAFBVV95cUxOTDE4dmZWeVI3YnllV0ZabC11VVE5ZnFnUjRhd291LUxfV1FQZ09Sb0hkdFlOZ0RkM0Z5SXVIN2NxTUx5VmdFZzR0UTRhelN3clY4TXlUQ0JEa2M2bnU4RU43TUpwc2N3T29VcEJHSldXbWVsRmhQbmlyNVBnZFh3VnNncmdoYjUzMzB6V2M2RWM?oc=5",
       "source": "UToday",
       "published_at": "2026-06-01 07:00"
      },
      {
       "title": "Twente-based PhD research aims to protect the Javan leopard",
       "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxQU3UxNG00eUZ2OERKMHpaYkluanl6dm1UdWJocHdrSGdDemtIeG5RNkF1bGc0QlNKeU1td3BjNEpyRFRGOEduZTRIWXMzV1B6MjR2bXVzVFM3cTlOeWtTempUY21TVlJsdXQ4WWY5aEYyR3BxQkYzRk9mWElEWnQ3a1NObzR0Uy1ZRG1WazdQQ3BBWWg1d0pPYkxBbw?oc=5",
       "source": "UToday",
       "published_at": "2026-05-27 07:00"
      },
      {
       "title": "Inter-Actief throws computers to mark anniversary",
       "url": "https://news.google.com/rss/articles/CBMikwFBVV95cUxQT29BdUtWMzZVZGRpYTF4N1lCalhLcUE2YnJnY1JHb0xVQ0EyTVpmYm9aR1FBaHN4QVFMcTBjRUJlcl81SmxWVFlGRndfbkdISVp4RXlSenl6Y29UdWduNE1fUE5Xa19Ca2owNFlsUllfbWhkbkVCZkVKaGExM24yOW16NFZsbmtjMUk0cjFUbkhNV2M?oc=5",
       "source": "UToday",
       "published_at": "2026-05-23 07:00"
      }
     ]
    }
   ],
   "count": 10
  },
  {
   "key": "morocco",
   "title": "Morocco",
   "icon": "🇲🇦",
   "note": null,
   "clusters": [
    {
     "label": "على",
     "articles": [
      {
       "title": "جنيف تحتضن جولة إضافية من جهود الترافع على قضية الصحراء المغربية",
       "url": "https://www.hespress.com/%d8%ac%d9%86%d9%8a%d9%81-%d8%aa%d8%ad%d8%aa%d8%b6%d9%86-%d8%ac%d9%88%d9%84%d8%a9-%d8%a5%d8%b6%d8%a7%d9%81%d9%8a%d8%a9-%d9%85%d9%86-%d8%ac%d9%87%d9%88%d8%af-%d8%a7%d9%84%d8%aa%d8%b1%d8%a7%d9%81%d8%b9-1804271.html",
       "source": "Hespress",
       "published_at": "2026-09-08 23:00"
      },
      {
       "title": "بعد 3 سنوات على \"زلزال الحوز\" .. أسر متضررة تنتظر تسوية الملفات",
       "url": "https://www.hespress.com/%d8%a8%d8%b9%d8%af-3-%d8%b3%d9%86%d9%88%d8%a7%d8%aa-%d8%b9%d9%84%d9%89-%d8%b2%d9%84%d8%b2%d8%a7%d9%84-%d8%a7%d9%84%d8%ad%d9%88%d8%b2-%d8%a3%d8%b3%d8%b1-%d9%85%d8%aa%d8%b6%d8%b1%d8%b1%d8%a9-1803915.html",
       "source": "Hespress",
       "published_at": "2026-09-08 22:00"
      }
     ]
    },
    {
     "label": "البيطار · البام",
     "articles": [
      {
       "title": "البيطار: \"البام\" يطالب بتغيير المسار وقطع الطريق أمام تضارب المصالح",
       "url": "https://www.hespress.com/%d8%a7%d9%84%d8%a8%d9%8a%d8%b7%d8%a7%d8%b1-%d8%a7%d9%84%d8%a8%d8%a7%d9%85-%d9%8a%d8%b7%d8%a7%d9%84%d8%a8-%d8%a8%d8%aa%d8%ba%d9%8a%d9%8a%d8%b1-%d8%a7%d9%84%d9%85%d8%b3%d8%a7%d8%b1-%d9%88%d9%82-1804278.html",
       "source": "Hespress",
       "published_at": "2026-09-08 22:11"
      },
      {
       "title": "لقاء خاص | البيطار وبرنامج البام",
       "url": "https://www.hespress.com/%d9%84%d9%82%d8%a7%d8%a1-%d8%ae%d8%a7%d8%b5-%d8%a7%d9%84%d8%a8%d9%8a%d8%b7%d8%a7%d8%b1-%d9%88%d8%a8%d8%b1%d9%86%d8%a7%d9%85%d8%ac-%d8%a7%d9%84%d8%a8%d8%a7%d9%85-1804283.html",
       "source": "Hespress",
       "published_at": "2026-09-08 22:08"
      }
     ]
    },
    {
     "label": "Conseil",
     "articles": [
      {
       "title": "À 50 jours du vote sur la Minurso, où en est le Maroc avec les membres du Conseil de sécurité de l’ONU ?",
       "url": "https://telquel.ma/2026/09/08/a-50-jours-du-vote-sur-la-minurso-ou-en-est-le-maroc-avec-les-membres-du-conseil-de-securite-de-lonu_2006325",
       "source": "TelQuel",
       "published_at": "2026-09-08 16:36"
      },
      {
       "title": "Aide au logement, enseignement supérieur et armes chimiques au menu du Conseil de gouvernement jeudi",
       "url": "https://telquel.ma/instant-t/2026/09/08/aide-au-logement-enseignement-superieur-et-armes-chimiques-au-menu-du-conseil-de-gouvernement-jeudi_2006375/",
       "source": "TelQuel",
       "published_at": "2026-09-08 16:07"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "حقيقة مواجهة مسلحة في الحسيمة",
       "url": "https://www.hespress.com/%d8%ad%d9%82%d9%8a%d9%82%d8%a9-%d9%85%d9%88%d8%a7%d8%ac%d9%87%d8%a9-%d9%85%d8%b3%d9%84%d8%ad%d8%a9-%d9%81%d9%8a-%d8%a7%d9%84%d8%ad%d8%b3%d9%8a%d9%85%d8%a9-1804334.html",
       "source": "Hespress",
       "published_at": "2026-09-08 23:49"
      },
      {
       "title": "بايتاس وتجويد حياة المغاربة",
       "url": "https://www.hespress.com/%d8%a8%d8%a7%d9%8a%d8%aa%d8%a7%d8%b3-%d9%88%d8%aa%d8%ac%d9%88%d9%8a%d8%af-%d8%ad%d9%8a%d8%a7%d8%a9-%d8%a7%d9%84%d9%85%d8%ba%d8%a7%d8%b1%d8%a8%d8%a9-1804323.html",
       "source": "Hespress",
       "published_at": "2026-09-08 23:35"
      },
      {
       "title": "\"الحمامة\" تعد بإصلاح التعليم والصحة من مدارس الريادة إلى طب الأسرة",
       "url": "https://www.hespress.com/%d8%a7%d9%84%d8%ad%d9%85%d8%a7%d9%85%d8%a9-%d8%aa%d8%b9%d8%af-%d8%a8%d8%a5%d8%b5%d9%84%d8%a7%d8%ad-%d8%a7%d9%84%d8%aa%d8%b9%d9%84%d9%8a%d9%85-%d9%88%d8%a7%d9%84%d8%b5%d8%ad%d8%a9-%d9%85%d9%86-1804286.html",
       "source": "Hespress",
       "published_at": "2026-09-08 23:30"
      },
      {
       "title": "\"دار زرياب\" تفتح مكتبة في مراكش",
       "url": "https://www.hespress.com/%d8%af%d8%a7%d8%b1-%d8%b2%d8%b1%d9%8a%d8%a7%d8%a8-%d8%aa%d9%81%d8%aa%d8%ad-%d9%85%d9%83%d8%aa%d8%a8%d8%a9-%d9%81%d9%8a-%d9%85%d8%b1%d8%a7%d9%83%d8%b4-1804162.html",
       "source": "Hespress",
       "published_at": "2026-09-08 23:22"
      },
      {
       "title": "طلبة طب الأسنان يحتجون بالبيضاء",
       "url": "https://www.hespress.com/%d8%b7%d9%84%d8%a8%d8%a9-%d8%b7%d8%a8-%d8%a7%d9%84%d8%a3%d8%b3%d9%86%d8%a7%d9%86-%d9%8a%d8%ad%d8%aa%d8%ac%d9%88%d9%86-%d8%a8%d8%a7%d9%84%d8%a8%d9%8a%d8%b6%d8%a7%d8%a1-4-1804295.html",
       "source": "Hespress",
       "published_at": "2026-09-08 22:46"
      },
      {
       "title": "أبرشية الرباط تنتظر تحقيق الفاتيكان",
       "url": "https://www.hespress.com/%d8%a3%d8%a8%d8%b1%d8%b4%d9%8a%d8%a9-%d8%a7%d9%84%d8%b1%d8%a8%d8%a7%d8%b7-%d8%aa%d9%86%d8%aa%d8%b8%d8%b1-%d8%aa%d8%ad%d9%82%d9%8a%d9%82-%d8%a7%d9%84%d9%81%d8%a7%d8%aa%d9%8a%d9%83%d8%a7%d9%86-1803906.html",
       "source": "Hespress",
       "published_at": "2026-09-08 22:03"
      },
      {
       "title": "غوتيريش يحفز \"المحادثات الأوكرانية\"",
       "url": "https://www.hespress.com/%d8%ba%d9%88%d8%aa%d9%8a%d8%b1%d9%8a%d8%b4-%d9%8a%d8%ad%d9%81%d8%b2-%d8%a7%d9%84%d9%85%d8%ad%d8%a7%d8%af%d8%ab%d8%a7%d8%aa-%d8%a7%d9%84%d8%a3%d9%88%d9%83%d8%b1%d8%a7%d9%86%d9%8a%d8%a9-1804228.html",
       "source": "Hespress",
       "published_at": "2026-09-08 21:55"
      },
      {
       "title": "اللحوم تشعل حملة الرئاسة البرازيلية",
       "url": "https://www.hespress.com/%d8%a7%d9%84%d9%84%d8%ad%d9%88%d9%85-%d8%aa%d8%b4%d8%b9%d9%84-%d8%ad%d9%85%d9%84%d8%a9-%d8%a7%d9%84%d8%b1%d8%a6%d8%a7%d8%b3%d8%a9-%d8%a7%d9%84%d8%a8%d8%b1%d8%a7%d8%b2%d9%8a%d9%84%d9%8a%d8%a9-1804036.html",
       "source": "Hespress",
       "published_at": "2026-09-08 21:44"
      },
      {
       "title": "Foot : Sofyan Amrabat annonce se mettre en retrait de la sélection tant que Ouahbi sera sélectionneur",
       "url": "https://telquel.ma/instant-t/2026/09/08/sofyan-amrabat-annonce-se-mettre-en-retrait-de-la-selection-tant-que-ouahbi-sera-selectionneur_2006409/",
       "source": "TelQuel",
       "published_at": "2026-09-08 16:49"
      },
      {
       "title": "7-Octobre : Netanyahu critiqué après un article le disant informé d'une attaque à venir",
       "url": "https://telquel.ma/instant-t/2026/09/08/7-octobre-netanyahu-critique-apres-un-article-le-disant-informe-dune-attaque-a-venir_2006406/",
       "source": "TelQuel",
       "published_at": "2026-09-08 16:43"
      },
      {
       "title": "CMT : un titre en suspens qui créé du suspense",
       "url": "https://telquel.ma/2026/09/08/cmt-un-titre-en-suspens-qui-cree-du-suspense_2006373",
       "source": "TelQuel",
       "published_at": "2026-09-08 15:55"
      },
      {
       "title": "[Archive] How Hassan II marginalized philosophy in Morocco",
       "url": "https://telquel.ma/2026/09/08/archive-how-hassan-ii-marginalized-philosophy-in-morocco_1999230",
       "source": "TelQuel",
       "published_at": "2026-09-08 15:48"
      }
     ]
    }
   ],
   "count": 18
  },
  {
   "key": "netherlands",
   "title": "The Netherlands",
   "icon": "🇳🇱",
   "note": null,
   "clusters": [
    {
     "label": "Schiphol",
     "articles": [
      {
       "title": "Luchtvaartstoring treft tienduizenden reizigers en raakt ook Schiphol hard",
       "url": "https://www.telegraaf.nl/financieel/luchtvaartstoring-treft-tienduizenden-reizigers-en-raakt-ook-schiphol-hard/161175722.html",
       "source": "de Telegraaf",
       "published_at": "2026-09-08 19:35"
      },
      {
       "title": "Kamer wil luchtvaartsector toch weren uit omwonendenraad Schiphol",
       "url": "https://www.telegraaf.nl/politiek/kamer-wil-luchtvaartsector-toch-weren-uit-omwonendenraad-schiphol/161174426.html",
       "source": "de Telegraaf",
       "published_at": "2026-09-08 18:47"
      },
      {
       "title": "Schiphol schrapt 58 vluchten vanwege storing bij Britse luchtverkeersleiding",
       "url": "https://www.nu.nl/economie/6409088/schiphol-schrapt-58-vluchten-vanwege-storing-bij-britse-luchtverkeersleiding.html",
       "source": "NU.nl",
       "published_at": "2026-09-08 17:39"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "Netanyahu zou zijn gewaarschuwd voor Hamas-aanval op 7 oktober, premier ontkent",
       "url": "https://www.nu.nl/midden-oostenconflict/6409100/netanyahu-zou-zijn-gewaarschuwd-voor-hamas-aanval-op-7-oktober-premier-ontkent.html",
       "source": "NU.nl",
       "published_at": "2026-09-08 19:55"
      },
      {
       "title": "Duizenden Duitsers protesteren tegen AfD na grote verkiezingsoverwinning",
       "url": "https://www.nu.nl/buitenland/6409092/duizenden-duitsers-protesteren-tegen-afd-na-grote-verkiezingsoverwinning.html",
       "source": "NU.nl",
       "published_at": "2026-09-08 18:38"
      },
      {
       "title": "Inburgeringsexamen Nederlands spreken is drukte van jewelste: ’Lijkt meer op een feest dan op een examen’",
       "url": "https://www.telegraaf.nl/binnenland/inburgeringsexamen-nederlands-spreken-is-drukte-van-jewelste-lijkt-meer-op-een-feest-dan-op-een-examen/161080810.html",
       "source": "de Telegraaf",
       "published_at": "2026-09-08 17:45"
      },
      {
       "title": "Landelijke ov-staking en wegwerkzaamheden: 'Hou rekening met vertraging'",
       "url": "https://www.nu.nl/binnenland/6409010/landelijke-ov-staking-en-wegwerkzaamheden-hou-rekening-met-vertraging.html",
       "source": "NU.nl",
       "published_at": "2026-09-08 16:50"
      }
     ]
    }
   ],
   "count": 7
  },
  {
   "key": "mideast",
   "title": "Iran & Middle East",
   "icon": "🌍",
   "note": null,
   "clusters": [
    {
     "label": "Israeli · Ban",
     "articles": [
      {
       "title": "Politics live: Australia to impose ‘targeted measures’ against Israeli settler violence but no ‘blanket-style import ban’",
       "url": "https://www.theguardian.com/australia-news/live/2026/sep/09/coalition-victoria-energy-bills-labor-one-nation-super-digital-duty-of-care-ntwnfb",
       "source": "Guardian World",
       "published_at": "2026-09-08 23:41"
      },
      {
       "title": "Paul Adams: British-Israeli relations at lowest ebb in decades",
       "url": "https://www.bbc.co.uk/news/articles/c5ydlex9yn3o?at_medium=RSS&at_campaign=rss",
       "source": "BBC World",
       "published_at": "2026-09-08 21:46"
      },
      {
       "title": "What the UK ban on goods from illegal Israeli settlements really means",
       "url": "https://www.aljazeera.com/video/newsfeed/2026/9/8/what-the-uk-ban-on-goods-from-illegal-israeli-settlements-really-means?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-09-08 21:35"
      },
      {
       "title": "UK announces sanctions on West Bank settlements prompting furious Israeli response",
       "url": "https://www.bbc.co.uk/news/articles/c4g7zen0vveo?at_medium=RSS&at_campaign=rss",
       "source": "BBC World",
       "published_at": "2026-09-08 19:11"
      },
      {
       "title": "UK accuses Israeli ‘terrorists’ of ethnic cleansing in West Bank with government backing",
       "url": "https://www.theguardian.com/world/2026/sep/08/uk-accuses-israeli-terrorists-ethnic-cleansing-west-bank-government-backing",
       "source": "Guardian World",
       "published_at": "2026-09-08 19:00"
      }
     ]
    },
    {
     "label": "Bank · West",
     "articles": [
      {
       "title": "Where is Israel's proposed West Bank settlement the UK opposes?",
       "url": "https://www.bbc.co.uk/news/videos/c74k1lw9nwko?at_medium=RSS&at_campaign=rss",
       "source": "BBC World",
       "published_at": "2026-09-08 16:45"
      },
      {
       "title": "In West Bank, date farmers weigh impact of UK sanctions on Israeli settlers",
       "url": "https://www.bbc.co.uk/news/articles/cvgy6gd228vo?at_medium=RSS&at_campaign=rss",
       "source": "BBC World",
       "published_at": "2026-09-08 15:36"
      }
     ]
    },
    {
     "label": "Israel · Sanctions",
     "articles": [
      {
       "title": "Burnham says Britain will ‘continue to act in support of our values’ after UK launches sanctions on Israel – as it happened",
       "url": "https://www.theguardian.com/politics/live/2026/sep/08/uk-us-trade-israel-sanctions-labour-ed-miliband-farage-latest-news-updates",
       "source": "Guardian World",
       "published_at": "2026-09-08 19:06"
      },
      {
       "title": "Israel to close British consulate in Jerusalem after sanctions announced",
       "url": "https://www.theguardian.com/world/2026/sep/08/israel-close-british-consulate-jerusalem-sanctions",
       "source": "Guardian World",
       "published_at": "2026-09-08 16:55"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "US says Iranian tankers destroyed after missile attacks on American warship",
       "url": "https://www.theguardian.com/us-news/2026/sep/08/iran-underwater-drone-strait-of-hormuz",
       "source": "Guardian World",
       "published_at": "2026-09-08 22:54"
      },
      {
       "title": "What’s happening in the Yemen war?",
       "url": "https://www.aljazeera.com/video/newsfeed/2026/9/8/09-08-hosted-yemen-explainer?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-09-08 20:13"
      },
      {
       "title": "Ed Miliband has overturned decades of Foreign Office inertia on illegal Israeli settlements",
       "url": "https://www.theguardian.com/world/2026/sep/08/ed-miliband-overturned-decades-foreign-office-inertia-illegal-israeli-settlements",
       "source": "Guardian World",
       "published_at": "2026-09-08 18:34"
      }
     ]
    }
   ],
   "count": 12
  },
  {
   "key": "ukraine",
   "title": "Ukraine War",
   "icon": "🇺🇦",
   "note": null,
   "clusters": [
    {
     "label": "Ukraine · Support",
     "articles": [
      {
       "title": "Ukraine to sign contracts for around 1,000 Patriot missiles with partner support and EU loan funding, defense minister says",
       "url": "https://kyivindependent.com/ukraine-to-sign-contracts-for-around-1-000-patriot-missiles-with-partner-support-and-eu-loan-funding-defense-minister-says/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-08 19:12"
      },
      {
       "title": "Ukraine war latest: Russia's deadline to capture Donbas slips yet again",
       "url": "https://kyivindependent.com/ukraine-war-latest-russias-deadline-to-capture-donbas-slips-yet-again/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-08 17:49"
      },
      {
       "title": "Ukraine’s prosecutor general quits after anti-corruption agents raid his office",
       "url": "https://www.theguardian.com/world/2026/sep/08/ukraine-prosecutor-general-ruslan-kravchenko-quits-anti-corruption-agents-raid-office",
       "source": "Guardian World",
       "published_at": "2026-09-08 17:00"
      },
      {
       "title": "Remilitarisation and support for Ukraine must not slacken, US tells Europe",
       "url": "https://www.theguardian.com/politics/2026/sep/08/uk-commits-100m-bolster-ukraine-air-defences-russia-war",
       "source": "Guardian World",
       "published_at": "2026-09-08 16:57"
      },
      {
       "title": "IMF report groups Moldova with EU applicants ahead of Ukraine",
       "url": "https://kyivindependent.com/imf-report-groups-moldova-with-eu-applicants-ahead-of-ukraine/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-08 16:28"
      }
     ]
    },
    {
     "label": "Russian · Kyiv",
     "articles": [
      {
       "title": "Police bodycam captures Russian missile strike on Kyiv",
       "url": "https://www.aljazeera.com/video/newsfeed/2026/9/8/police-bodycam-captures-russian-missile-strike-on-kyiv?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-09-08 20:43"
      },
      {
       "title": "Russian drone violates Moldovan and Romanian airspace, crashes in Moldova",
       "url": "https://kyivindependent.com/russian-drone-violates-moldovan-and-romanian-airspace-crashes-in-moldova/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-08 17:23"
      },
      {
       "title": "Ukrainian TV channel building hit by Russian drone as five killed in Kyiv",
       "url": "https://www.bbc.co.uk/news/articles/cn8m1k7p3v7o?at_medium=RSS&at_campaign=rss",
       "source": "BBC World",
       "published_at": "2026-09-08 17:10"
      }
     ]
    },
    {
     "label": "Zelensky",
     "articles": [
      {
       "title": "Zelensky, Norway’s Store discuss air defense, Freyja program ahead of King Harald’s funeral",
       "url": "https://kyivindependent.com/zelensky-norways-store-discuss-air-defense-freyja-program-ahead-of-king-haralds-funeral/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-08 21:56"
      },
      {
       "title": "Germany 'ready to provide missiles for Patriots,' Zelensky says",
       "url": "https://kyivindependent.com/germany-ready-to-provide-missiles-for-patriots-zelensky-says/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-08 16:40"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "Xi, Putin pledge stronger ties with North Korea on founding anniversary",
       "url": "https://kyivindependent.com/xi-putin-pledge-stronger-ties-with-north-korea-on-founding-anniversary/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-08 23:30"
      },
      {
       "title": "Russia's 160-year war on Ukrainian books",
       "url": "https://kyivindependent.com/russias-160-year-war-on-ukrainian-books/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-08 18:07"
      }
     ]
    }
   ],
   "count": 12
  }
 ]
};
