// Generated by generate_data.py — do not edit; see data.json.
window.__NEWS__ = {
 "date": "Sunday 4 October 2026",
 "generated_at": "19:29 UTC",
 "error": null,
 "total_stories": 71,
 "fx": {
  "pair": "EUR/MAD",
  "rate": 11.138,
  "change_pct": 0.0
 },
 "lanes": [
  {
   "key": "ai",
   "title": "AI & Models",
   "icon": "🤖",
   "note": null,
   "clusters": [
    {
     "label": "Qwen",
     "articles": [
      {
       "title": "poorman inference engine for 16GB GPU and 35B moe Qwen 3.6for coding",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wxllvu/poorman_inference_engine_for_16gb_gpu_and_35b_moe/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-10-04 17:40"
      },
      {
       "title": "I took antirez's ds4, stripped it down to Qwen3.8 Flash Next on Metal, ported a bunch of improvements, and it's now ~10% faster with bit-exact output",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wxkojd/i_took_antirezs_ds4_stripped_it_down_to_qwen38/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-10-04 17:02"
      },
      {
       "title": "Qwen3.5 arch implementation in FPGA fabric for 9B/27B INT4 models on relatively cheap eBay mining hardware",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wxken1/qwen35_arch_implementation_in_fpga_fabric_for/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-10-04 16:51"
      },
      {
       "title": "A Strata fork for IBM AC922 running Qwen3.8-FN UD-Q4_K_XL is doing up to 7,357 tk/s prefill and 113 tk/s decode",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wxjs47/a_strata_fork_for_ibm_ac922_running_qwen38fn_udq4/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-10-04 16:25"
      }
     ]
    },
    {
     "label": "Clef · Cloudflare",
     "articles": [
      {
       "title": "Benchmarking decision models is fun - Clef Q8 vs Jev",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wxloam/benchmarking_decision_models_is_fun_clef_q8_vs_jev/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-10-04 17:43"
      },
      {
       "title": "Cloudflare/clef · 1156 ♥",
       "url": "https://huggingface.co/Cloudflare/clef",
       "source": "HF new models",
       "published_at": "2026-09-30 21:15"
      },
      {
       "title": "Cloudflare/clef-flash · 417 ♥",
       "url": "https://huggingface.co/Cloudflare/clef-flash",
       "source": "HF new models",
       "published_at": "2026-09-30 21:15"
      }
     ]
    },
    {
     "label": "Scratch",
     "articles": [
      {
       "title": "Update #4: Post training yandex/AliceAI-80B-A3B [instruct!] from scratch",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wxlytt/update_4_post_training_yandexaliceai80ba3b/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-10-04 17:55"
      },
      {
       "title": "I trained a 3.87B MoE (1.45B active) from scratch on only 86.5B tokens",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wxiy8y/i_trained_a_387b_moe_145b_active_from_scratch_on/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-10-04 15:50"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "Micron CEO Says Memory Supply Will Be Much Tighter in 2027 and 2028 Than in 2026",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wxma3a/micron_ceo_says_memory_supply_will_be_much/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-10-04 18:08"
      },
      {
       "title": "LLM Inference Dashboard",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wxm2og/llm_inference_dashboard/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-10-04 18:00"
      },
      {
       "title": "LFM2.5 2.6b vs MiniCPM5 2b",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wxlw2c/lfm25_26b_vs_minicpm5_2b/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-10-04 17:52"
      },
      {
       "title": "Built a quick, sub-15ms Rust CLI/TUI to pack repos into prompts without burning 40k tokens on lockfiles and junk",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wxl36c/built_a_quick_sub15ms_rust_clitui_to_pack_repos/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-10-04 17:18"
      },
      {
       "title": "NJ’s former Lt Gov is using AI to say he’s innocent of sexual harassment",
       "url": "https://www.theverge.com/ai-artificial-intelligence/1004549/well-if-ai-said-it-it-must-be-true",
       "source": "Verge AI",
       "published_at": "2026-10-04 16:16"
      },
      {
       "title": "Aleph-Alpha/Kolibri-1 · 368 ♥",
       "url": "https://huggingface.co/Aleph-Alpha/Kolibri-1",
       "source": "HF new models",
       "published_at": "2026-10-02 05:54"
      },
      {
       "title": "PSRben/VisionHOPE · 400 ♥",
       "url": "https://huggingface.co/PSRben/VisionHOPE",
       "source": "HF new models",
       "published_at": "2026-09-29 07:28"
      },
      {
       "title": "SupersonicLabs/Julia-1 · 412 ♥",
       "url": "https://huggingface.co/SupersonicLabs/Julia-1",
       "source": "HF new models",
       "published_at": "2026-09-23 15:29"
      },
      {
       "title": "Contrastive-LM/CLM-v0.1-8B · 707 ♥",
       "url": "https://huggingface.co/Contrastive-LM/CLM-v0.1-8B",
       "source": "HF new models",
       "published_at": "2026-09-21 20:09"
      }
     ]
    }
   ],
   "count": 18
  },
  {
   "key": "utoday",
   "title": "UTwente (UToday)",
   "icon": "📍",
   "note": null,
   "clusters": [
    {
     "label": "Grote · Bestuursfotoverkiezing",
     "articles": [
      {
       "title": "De Grote U-Today Bestuursfotoverkiezing 2026, de uitslag",
       "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxQNjU5OVlOSzctN0dKYlZ2ZVdzd2U1UWZCeEY0SXF3bzVfWTg0bXJqZGp0OGs2WUxSaGZlRVZLQjVSU2pZZGZXR1JsclBPZ1hFS1hQTVZmMXNxYTVOQ0w3NEJyS2xjZlhTWTlJQTl2LWV3bGdCaHQ2U1dLZldxeUxVVkpQYjA0LU1xY0VqMi1RU1RIM2RJVzdYdFd6UQ?oc=5",
       "source": "UToday",
       "published_at": "2026-06-25 07:00"
      },
      {
       "title": "Terug van (nooit) weggeweest: De Grote U-Today Bestuursfotoverkiezing",
       "url": "https://news.google.com/rss/articles/CBMioAFBVV95cUxNMUh5OFBxVGtqWTNXUG1kTUIxTFZSN0xwd0JWWXk4elRvdi1mZW4tYUxhU0VBOGRfQVA3bXpqaURjTUJjR1Ftb0M4QkZpQ01Mc2dZTTQzT29laXNENldKNzhOcFJ0NUtOYlNKT2dYNVYtWVRaZjU3SlAwQWs3R09TZjJaNHg5QjhuMmVPTlJjMEMzRmlXUm1Sd3luU0tGcWst?oc=5",
       "source": "UToday",
       "published_at": "2026-05-27 07:00"
      }
     ]
    },
    {
     "label": "Online",
     "articles": [
      {
       "title": "Nieuwe hulpwijzer sociale veiligheid online",
       "url": "https://news.google.com/rss/articles/CBMiggFBVV95cUxQUks5UG5DX2FNZkFqZ0dvaWxfM3UzempKbkVKOTVELTZMX3liM24xWTdzYnRMV3JQajlTTjVlc0JuMTc0NzIyUzNqVTFXaTJvcEUzVlB4YzR5bHBmWW1RbUxaWk1vd25JeHgxWXd2QTJVRXFoWXgxLUpFR3B0LUtlNlZ3?oc=5",
       "source": "UToday",
       "published_at": "2026-05-28 07:00"
      },
      {
       "title": "New social safety support guide now online",
       "url": "https://news.google.com/rss/articles/CBMigAFBVV95cUxQQkhTYkN4eVpBWm5GR1NpaDBJNUI1S1ZmVml0N1RfcjV2cmpORHBja2dYS2VXekhQQ0pKMEtib0JxekxlbHhpQS1BaGlybzFZeHQxQUJBRlktU0JNSm5tNkdPckRTODRFbDN3TTltVlZDemp1Y2cwZWFtSnVVaVhkRA?oc=5",
       "source": "UToday",
       "published_at": "2026-05-28 07:00"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "Zes Nederlandse universiteiten betalen nog steeds tonnen voor instituut in Rusland",
       "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxOaHNwWmpjMHZGdkFMcldBRGo1TFZ3ODgtS3RGNmwtbW1PYzRiQjhmVGNPbG1Yd2lSdVJsWGNjbDc5NjNldVBORjJuYXhzWGlRUVUwT0pIaEtKd3c5RnlXSDhZT3NqVE56aEpNOTlCR2RDOXVzd0gyUi11d0pLSVlkdGktcmI2V3ZrdHJRSXBhYlRtNDlsb0RhNTAtbVNnOWllU0pFSDRLX05QU1hMWjJ5cU1fNEpWUQ?oc=5",
       "source": "UToday",
       "published_at": "2026-10-02 13:28"
      },
      {
       "title": "Vraagstelling",
       "url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE9qbFRzSWdWS3V2RUZILUhEX2FfLXhUMjRTV3BfTVMyVXZCek94OE9OMllUeHp0NmoxeUE4S3lHTVcxVm5WQlFTWFZJMUVpUzRjS0NBTklUTlhmZDA2Znc?oc=5",
       "source": "UToday",
       "published_at": "2026-10-02 11:12"
      },
      {
       "title": "TU Delft negeert waarschuwingen en stopt gevoelige gegevens van (oud)studenten in de cloud",
       "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxNRXY0TDBncDdjdWlsVDJQOTM5S2tvVDdTc3dSQlNqdGZ3VW1EWU1hcTRGNHAzamVUMDdzUUxuZ1FZSDkwcHk1dWhpS1lWY3Jpc1duSkF1WUkwakY0eTRpVTZCZUlNd0xoQUp6WTBZYS1vWk9LRHlveURnWUU5a2hiY282SWxDMDM4dk40d2diaF9nRnAyNHoySUtYeGRlcG1LdG1CY01XVkQ2NkVoSWo1UDdZbXFfcS16bWMwWlJn?oc=5",
       "source": "UToday",
       "published_at": "2026-10-02 07:26"
      },
      {
       "title": "Homoacceptatie; meer zichtbaarheid nodig op UT",
       "url": "https://news.google.com/rss/articles/CBMihAFBVV95cUxObzVkeUlEangtWE5iMkVSNGxELWJiS1VZTmpBVkRBREV5dlFrOHVvSjdkRDVBV3JxakZ0TDRoQjA2U2JHci1oY1Z5Rng0bUR5RVRweU9TdEE5RndxTTFVTlRLd1Y1OWYyY04zc1p3MzJZb2ZBYXg2ZndTcEVpVTdvbkRONjk?oc=5",
       "source": "UToday",
       "published_at": "2026-09-29 14:50"
      },
      {
       "title": "Elfbierentocht vs alcoholconvenant: ‘Cola mag ook’",
       "url": "https://news.google.com/rss/articles/CBMijAFBVV95cUxQRjNkNzM5VjZVV3ZEaC05UzRpVG9kLUZFQkc3Nzk3UDlqWXlPaFNzZFVieXBpbWlyTDRQcEFvNVVlRmJtX3BTTXNUZlctWGlQSzA1NXVER2NYcWJDaU1valZ1T3AxR0NsOWtHZmxpcHZvX1VJd0l5cFRqNGlSdG9mZDhEU2VyOG13bHAxZg?oc=5",
       "source": "UToday",
       "published_at": "2026-06-10 07:00"
      },
      {
       "title": "Vermoeidheid na borstkanker speelt veel vrouwen parten",
       "url": "https://news.google.com/rss/articles/CBMikAFBVV95cUxOTDE4dmZWeVI3YnllV0ZabC11VVE5ZnFnUjRhd291LUxfV1FQZ09Sb0hkdFlOZ0RkM0Z5SXVIN2NxTUx5VmdFZzR0UTRhelN3clY4TXlUQ0JEa2M2bnU4RU43TUpwc2N3T29VcEJHSldXbWVsRmhQbmlyNVBnZFh3VnNncmdoYjUzMzB6V2M2RWM?oc=5",
       "source": "UToday",
       "published_at": "2026-06-01 07:00"
      }
     ]
    }
   ],
   "count": 10
  },
  {
   "key": "morocco",
   "title": "Morocco",
   "icon": "🇲🇦",
   "note": null,
   "clusters": [
    {
     "label": "على",
     "articles": [
      {
       "title": "بنعلي: \"الخيار الديمقراطي\" يراهن على إضافة نوعية للعمل البرلماني",
       "url": "https://www.hespress.com/%d8%a8%d9%86%d8%b9%d9%84%d9%8a-%d8%a7%d9%84%d8%ae%d9%8a%d8%a7%d8%b1-%d8%a7%d9%84%d8%af%d9%8a%d9%85%d9%82%d8%b1%d8%a7%d8%b7%d9%8a-%d9%8a%d8%b1%d8%a7%d9%87%d9%86-%d8%b9%d9%84%d9%89-%d8%a5%d8%b6-1817893.html",
       "source": "Hespress",
       "published_at": "2026-10-04 19:00"
      },
      {
       "title": "للأسبوع الخامس على التوالي .. الدرهم يواصل التراجع أمام اليورو والدولار",
       "url": "https://www.hespress.com/%d9%84%d9%84%d8%a3%d8%b3%d8%a8%d9%88%d8%b9-%d8%a7%d9%84%d8%ae%d8%a7%d9%85%d8%b3-%d8%b9%d9%84%d9%89-%d8%a7%d9%84%d8%aa%d9%88%d8%a7%d9%84%d9%8a-%d8%a7%d9%84%d8%af%d8%b1%d9%87%d9%85-%d9%8a%d9%88%d8%a7-1817924.html",
       "source": "Hespress",
       "published_at": "2026-10-04 17:57"
      },
      {
       "title": "زعيم كوريا الشمالية يشرف على إطلاق صاروخ بالذكاء الاصطناعي",
       "url": "https://www.hespress.com/%d8%b2%d8%b9%d9%8a%d9%85-%d9%83%d9%88%d8%b1%d9%8a%d8%a7-%d8%a7%d9%84%d8%b4%d9%85%d8%a7%d9%84%d9%8a%d8%a9-%d9%8a%d8%b4%d8%b1%d9%81-%d8%b9%d9%84%d9%89-%d8%a5%d8%b7%d9%84%d8%a7%d9%82-%d8%b5%d8%a7%d8%b1-1817898.html",
       "source": "Hespress",
       "published_at": "2026-10-04 16:43"
      }
     ]
    },
    {
     "label": "Pam · Rni",
     "articles": [
      {
       "title": "Élections 2026 : le PAM veut tourner la page RNI",
       "url": "https://telquel.ma/2026/10/03/elections-2026-le-pam-veut-tourner-la-page-rni_2011385",
       "source": "TelQuel",
       "published_at": "2026-10-03 16:29"
      },
      {
       "title": "Formation du gouvernement : le PAM rejette la participation du RNI, selon Baraka",
       "url": "https://telquel.ma/instant-t/2026/10/03/formation-du-gouvernement-le-pam-rejette-la-participation-du-rni-selon-baraka_2011380/",
       "source": "TelQuel",
       "published_at": "2026-10-03 15:01"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "التحرش الجنسي يلاحق الشرطة الهندية",
       "url": "https://www.hespress.com/%d8%a7%d9%84%d8%aa%d8%ad%d8%b1%d8%b4-%d8%a7%d9%84%d8%ac%d9%86%d8%b3%d9%8a-%d9%8a%d9%84%d8%a7%d8%ad%d9%82-%d8%a7%d9%84%d8%b4%d8%b1%d8%b7%d8%a9-%d8%a7%d9%84%d9%87%d9%86%d8%af%d9%8a%d8%a9-1817944.html",
       "source": "Hespress",
       "published_at": "2026-10-04 19:06"
      },
      {
       "title": "فرنسا تعلّق الدروس بمئات الثانويات",
       "url": "https://www.hespress.com/%d9%81%d8%b1%d9%86%d8%b3%d8%a7-%d8%aa%d8%b9%d9%84%d9%91%d9%82-%d8%a7%d9%84%d8%af%d8%b1%d9%88%d8%b3-%d8%a8%d9%85%d8%a6%d8%a7%d8%aa-%d8%a7%d9%84%d8%ab%d8%a7%d9%86%d9%88%d9%8a%d8%a7%d8%aa-1817834.html",
       "source": "Hespress",
       "published_at": "2026-10-04 18:31"
      },
      {
       "title": "نشرة إنذارية: زخات رعدية قوية بالمغرب",
       "url": "https://www.hespress.com/%d9%86%d8%b4%d8%b1%d8%a9-%d8%a5%d9%86%d8%b0%d8%a7%d8%b1%d9%8a%d8%a9-%d8%b2%d8%ae%d8%a7%d8%aa-%d8%b1%d8%b9%d8%af%d9%8a%d8%a9-%d9%82%d9%88%d9%8a%d8%a9-%d8%a8%d8%a7%d9%84%d9%85%d8%ba%d8%b1%d8%a8-3-1817959.html",
       "source": "Hespress",
       "published_at": "2026-10-04 18:00"
      },
      {
       "title": "الرئاسة الإيرانية تقبل استقالة وزير النفط",
       "url": "https://www.hespress.com/%d8%a7%d9%84%d8%b1%d8%a6%d8%a7%d8%b3%d8%a9-%d8%a7%d9%84%d8%a5%d9%8a%d8%b1%d8%a7%d9%86%d9%8a%d8%a9-%d8%aa%d9%82%d8%a8%d9%84-%d8%a7%d8%b3%d8%aa%d9%82%d8%a7%d9%84%d8%a9-%d9%88%d8%b2%d9%8a%d8%b1-%d8%a7-1817945.html",
       "source": "Hespress",
       "published_at": "2026-10-04 17:51"
      },
      {
       "title": "مقتل أكثر من 70 شخصا في معارك تعز",
       "url": "https://www.hespress.com/%d9%85%d9%82%d8%aa%d9%84-%d8%a3%d9%83%d8%ab%d8%b1-%d9%85%d9%86-70-%d8%b4%d8%ae%d8%b5%d8%a7-%d9%81%d9%8a-%d9%85%d8%b9%d8%a7%d8%b1%d9%83-%d8%aa%d8%b9%d8%b2-1817918.html",
       "source": "Hespress",
       "published_at": "2026-10-04 17:34"
      },
      {
       "title": "تشكيلة المنتخب المغربي أمام مالي",
       "url": "https://www.hespress.com/%d8%aa%d8%b4%d9%83%d9%8a%d9%84%d8%a9-%d8%a7%d9%84%d9%85%d9%86%d8%aa%d8%ae%d8%a8-%d8%a7%d9%84%d9%85%d8%ba%d8%b1%d8%a8%d9%8a-%d8%a3%d9%85%d8%a7%d9%85-%d9%85%d8%a7%d9%84%d9%8a-1817910.html",
       "source": "Hespress",
       "published_at": "2026-10-04 17:06"
      },
      {
       "title": "مقامة العكّاز",
       "url": "https://www.hespress.com/%d9%85%d9%8e%d9%82%d9%8e%d8%a7%d9%85%d9%8e%d8%a9%d9%8f-%d8%a7%d9%84%d8%b9%d9%8f%d9%83%d9%91%d8%a7%d8%b2%d9%90-1816992.html",
       "source": "Hespress",
       "published_at": "2026-10-04 17:03"
      },
      {
       "title": "مئات المهاجرين يختارون العودة إلى المغرب خلال إخلاء مخيم بسبتة",
       "url": "https://www.hespress.com/%d9%85%d8%a6%d8%a7%d8%aa-%d8%a7%d9%84%d9%85%d9%87%d8%a7%d8%ac%d8%b1%d9%8a%d9%86-%d9%8a%d8%ae%d8%aa%d8%a7%d8%b1%d9%88%d9%86-%d8%a7%d9%84%d8%b9%d9%88%d8%af%d8%a9-%d8%a5%d9%84%d9%89-%d8%a7%d9%84%d9%85-1817906.html",
       "source": "Hespress",
       "published_at": "2026-10-04 17:00"
      },
      {
       "title": "\"الغطاء الشجري\" يتراجع في طوكيو .. والحرارة تزداد قسوة",
       "url": "https://www.hespress.com/%d8%a7%d9%84%d8%ba%d8%b7%d8%a7%d8%a1-%d8%a7%d9%84%d8%b4%d8%ac%d8%b1%d9%8a-%d9%8a%d8%aa%d8%b1%d8%a7%d8%ac%d8%b9-%d9%81%d9%8a-%d8%b7%d9%88%d9%83%d9%8a%d9%88-%d9%88%d8%a7%d9%84%d8%ad%d8%b1%d8%a7-1817966.html",
       "source": "Hespress",
       "published_at": "2026-10-04 16:43"
      },
      {
       "title": "Vicenne d'Adil Bennani : 591 MDH de ventes, cap confirmé",
       "url": "https://telquel.ma/2026/10/02/vicenne-dadil-bennani-591-mdh-de-ventes-cap-confirme_2011374",
       "source": "TelQuel",
       "published_at": "2026-10-02 19:34"
      },
      {
       "title": "Au premier semestre 2026, plus de 71 milliards de dirhams ont été échangés via virements instantanés",
       "url": "https://telquel.ma/2026/10/02/au-premier-semestre-2026-plus-de-71-milliards-de-dirhams-ont-ete-echanges-via-virements-instantanes_2011297",
       "source": "TelQuel",
       "published_at": "2026-10-02 16:45"
      },
      {
       "title": "[Infographies] Élections : que pèsent, en voix, 15 ministres sortants ?",
       "url": "https://telquel.ma/2026/10/02/infographies-elections-que-pesent-en-voix-les-15-ministres-sortants_2011290",
       "source": "TelQuel",
       "published_at": "2026-10-02 16:12"
      },
      {
       "title": "[Tribune] Guerre et IA : quand la machine change la chaîne de décision",
       "url": "https://telquel.ma/2026/10/02/tribune-guerre-et-ia-quand-la-machine-change-la-chaine-de-decision_2010954",
       "source": "TelQuel",
       "published_at": "2026-10-02 15:55"
      }
     ]
    }
   ],
   "count": 18
  },
  {
   "key": "netherlands",
   "title": "The Netherlands",
   "icon": "🇳🇱",
   "note": null,
   "clusters": [
    {
     "label": "Dijk · Oranje",
     "articles": [
      {
       "title": "Van Dijk komt met zoontje het veld op en treedt toe tot club van 100 van Oranje",
       "url": "https://www.nu.nl/voetbal/6411985/van-dijk-komt-met-zoontje-het-veld-op-en-treedt-toe-tot-club-van-100-van-oranje.html",
       "source": "NU.nl",
       "published_at": "2026-10-04 18:53"
      },
      {
       "title": "Virgil van Dijk (35) speelt 100e interland voor het Nederlands elftal en ontvangt gouden schaal",
       "url": "https://www.telegraaf.nl/sport/voetbal/virgil-van-dijk-35-speelt-100e-interland-voor-het-nederlands-elftal-en-ontvangt-gouden-schaal/162572003.html",
       "source": "de Telegraaf",
       "published_at": "2026-10-04 17:50"
      },
      {
       "title": "Oranje begint met Lang, Koopmeiners en jubilaris Van Dijk tegen Servië",
       "url": "https://www.nu.nl/voetbal/6411979/oranje-begint-met-lang-koopmeiners-en-jubilaris-van-dijk-tegen-servie.html",
       "source": "NU.nl",
       "published_at": "2026-10-04 17:34"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "Annemarie van Gaal: asieldwangsommen helpen niet, dus waarom zouden we ze nog opleggen?",
       "url": "https://www.telegraaf.nl/opinie/annemarie-van-gaal-asieldwangsommen-helpen-niet-dus-waarom-zouden-we-ze-nog-opleggen/162531489.html",
       "source": "de Telegraaf",
       "published_at": "2026-10-04 16:45"
      }
     ]
    }
   ],
   "count": 4
  },
  {
   "key": "mideast",
   "title": "Iran & Middle East",
   "icon": "🌍",
   "note": null,
   "clusters": [
    {
     "label": "War · Iran",
     "articles": [
      {
       "title": "War on Iran: Is escalation more likely than a deal?",
       "url": "https://www.aljazeera.com/video/the-bottom-line/2026/10/4/war-on-iran-is-escalation-more-likely-than-a-deal-2?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-10-04 18:47"
      },
      {
       "title": "Yemen's government announces all-out war to reclaim land from Houthis",
       "url": "https://www.bbc.co.uk/news/articles/cx8dzj9vpp01o?at_medium=RSS&at_campaign=rss",
       "source": "BBC World",
       "published_at": "2026-10-04 16:51"
      },
      {
       "title": "Iran tells US: there is ‘no military solution’ to end the war",
       "url": "https://www.aljazeera.com/video/newsfeed/2026/10/4/iran-tells-us-there-is-no-military-solution-to-end-the-war?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-10-04 15:06"
      }
     ]
    },
    {
     "label": "Israel",
     "articles": [
      {
       "title": "As it happened: Israel condemns Green party passing ‘Zionism is racism’ as a ‘stain on history of UK’",
       "url": "https://www.theguardian.com/politics/live/2026/oct/04/conservatives-tories-conference-kemi-badenoch-james-cleverly-labour-jury-trials-green-party-zionism-uk-politics-latest-news-updates",
       "source": "Guardian World",
       "published_at": "2026-10-04 16:32"
      },
      {
       "title": "‘Did he know?’: Why Israel is rejecting an October 7 reckoning",
       "url": "https://www.aljazeera.com/opinions/2026/10/4/did-he-know-why-israel-is-rejecting-an-october-7-reckoning?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-10-04 15:22"
      }
     ]
    },
    {
     "label": "Gaza",
     "articles": [
      {
       "title": "Three years of genocide in Gaza through one man’s camera",
       "url": "https://www.aljazeera.com/video/newsfeed/2026/10/4/three-years-of-genocide-in-gaza-through-one-mans-camera?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-10-04 16:18"
      },
      {
       "title": "Court quashes block on mothers and children in Gaza joining families in UK",
       "url": "https://www.theguardian.com/politics/2026/oct/04/court-quashes-block-on-mothers-and-children-in-gaza-joining-families-in-uk",
       "source": "Guardian World",
       "published_at": "2026-10-04 11:00"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "Jerusalem Daily: Israeli forces arrest school children during raid",
       "url": "https://www.aljazeera.com/video/newsfeed/2026/10/4/jerusalem-daily-israeli-forces-arrest-school-children-during-raid?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-10-04 16:04"
      },
      {
       "title": "Why is fighting intensifying in Yemen’s Taiz governorate?",
       "url": "https://www.aljazeera.com/news/2026/10/4/why-is-fighting-intensifying-in-yemens-taiz-governorate?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-10-04 13:31"
      }
     ]
    }
   ],
   "count": 9
  },
  {
   "key": "ukraine",
   "title": "Ukraine War",
   "icon": "🇺🇦",
   "note": null,
   "clusters": [
    {
     "label": "Ukraine · Aid",
     "articles": [
      {
       "title": "Ukraine war latest: Germany supplies Kyiv with interceptors, air defense missiles in $1.5 billion aid package",
       "url": "https://kyivindependent.com/ukraine-war-latest-germany-supplies-kyiv-with-interceptors-air-defense-missiles-in-1-5-billion-aid-package/",
       "source": "Kyiv Independent",
       "published_at": "2026-10-04 17:24"
      },
      {
       "title": "Ukraine ready for US-backed talks with Russia: Zelenskyy",
       "url": "https://www.aljazeera.com/news/2026/10/4/ukraine-ready-for-us-backed-talks-with-russia-zelenskyy?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-10-04 17:17"
      },
      {
       "title": "Russia strikes Kyiv bridge as German chancellor visits Ukraine in show of support",
       "url": "https://www.theguardian.com/world/2026/oct/04/russia-strikes-kyiv-bridge-german-chancellor-merz-visits-ukraine",
       "source": "Guardian World",
       "published_at": "2026-10-04 16:12"
      },
      {
       "title": "Latvia's pro-Ukraine party wins parliamentary election by wide margin",
       "url": "https://kyivindependent.com/latvias-pro-ukraine-party-wins-parliamentary-election-by-wide-margin/",
       "source": "Kyiv Independent",
       "published_at": "2026-10-04 15:57"
      },
      {
       "title": "News from occupied Ukraine: Military delivers aid by drone to occupied Oleshky in second operation",
       "url": "https://kyivindependent.com/news-from-occupied-ukraine-military-delivers-aid-by-drone-to-occupied-oleshky-in-second-operation/",
       "source": "Kyiv Independent",
       "published_at": "2026-10-04 14:41"
      }
     ]
    },
    {
     "label": "Russia · Jet",
     "articles": [
      {
       "title": "Plague death triggers quarantine, mask mandates in Russia's Irkutsk region in Siberia",
       "url": "https://kyivindependent.com/plague-death-triggers-quarantine-mask-mandates-in-russias-irkutsk-region-in-siberia/",
       "source": "Kyiv Independent",
       "published_at": "2026-10-04 18:42"
      },
      {
       "title": "'Very dangerous moment' — Russia sharing jet-powered drone tech with North Korea, Zelensky says",
       "url": "https://kyivindependent.com/very-dangerous-moment-russia-sharing-jet-powered-drone-tech-with-north-korea-zelensky-says/",
       "source": "Kyiv Independent",
       "published_at": "2026-10-04 16:36"
      },
      {
       "title": "How Russia’s new jet drones are changing the threat to Kyiv",
       "url": "https://kyivindependent.com/how-russias-new-jet-drones-are-changing-the-threat-to-kyiv/",
       "source": "Kyiv Independent",
       "published_at": "2026-10-04 13:18"
      }
     ]
    },
    {
     "label": "Kyiv",
     "articles": [
      {
       "title": "Germany’s Merz in Kyiv announces $1.5B in aid, urges Putin to end war",
       "url": "https://www.aljazeera.com/video/newsfeed/2026/10/4/germany-merz-visits-kyiv-air-raids-ukraine?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-10-04 16:38"
      },
      {
       "title": "Watch: What we know about Russian strikes on Kyiv bridges",
       "url": "https://www.bbc.co.uk/news/videos/cmglwkyl9djyo?at_medium=RSS&at_campaign=rss",
       "source": "BBC World",
       "published_at": "2026-10-04 14:25"
      }
     ]
    },
    {
     "label": "Drones",
     "articles": [
      {
       "title": "Russian Su-35, Su-34 fighter jets hit by drones at airfield in Adygea, SBU says",
       "url": "https://kyivindependent.com/russian-su-35-su-34-fighter-jets-hit-by-drones-at-airfield-in-adygea-sbu-says/",
       "source": "Kyiv Independent",
       "published_at": "2026-10-04 15:13"
      },
      {
       "title": "Germany announces $1.46 billion in aid for Ukraine, including interceptor drones, air defense missiles",
       "url": "https://kyivindependent.com/germany-announces-1-46-billion-in-aid-for-ukraine-including-interceptor-drones/",
       "source": "Kyiv Independent",
       "published_at": "2026-10-04 13:18"
      }
     ]
    }
   ],
   "count": 12
  }
 ]
};
