// Generated by generate_data.py — do not edit; see data.json.
window.__NEWS__ = {
 "date": "Friday 18 September 2026",
 "generated_at": "05:41 UTC",
 "error": null,
 "total_stories": 78,
 "fx": {
  "pair": "EUR/MAD",
  "rate": 10.902,
  "change_pct": 0.0
 },
 "lanes": [
  {
   "key": "ai",
   "title": "AI & Models",
   "icon": "🤖",
   "note": null,
   "clusters": [
    {
     "label": "Qwen · Flash",
     "articles": [
      {
       "title": "dual 7900 xtx - some guy made a pretty optimized fork of lamacpp optimized for this setup Qwen 3.8 Q8 at 82 tokens / seconds decode",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wjd5hf/dual_7900_xtx_some_guy_made_a_pretty_optimized/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-18 02:00"
      },
      {
       "title": "what's the state of the art recipe for running Qwen3.8-Flash-Next with a pair of 3090s and a ton of system RAM rn?",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wjcnkv/whats_the_state_of_the_art_recipe_for_running/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-18 01:36"
      },
      {
       "title": "600tok/s single request on qwen3.6 35ba3b with Ninfer on an RTX Pro 6000. Anybody remember that Comcast ad \"stupid fast\"?",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wja9ml/600toks_single_request_on_qwen36_35ba3b_with/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-17 23:47"
      },
      {
       "title": "Qwen 3.8 Omni Flash",
       "url": "https://qwen.ai/blog?id=qwen3.8-omni-flash",
       "source": "Hacker News",
       "published_at": "2026-09-17 23:05"
      },
      {
       "title": "harshatheg/Qwen-2.5-1B-RLCD · 301 ♥",
       "url": "https://huggingface.co/harshatheg/Qwen-2.5-1B-RLCD",
       "source": "HF new models",
       "published_at": "2026-09-16 01:35"
      }
     ]
    },
    {
     "label": "Ternary · Bonsai",
     "articles": [
      {
       "title": "Ternary Bonsai is a headless chicken",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wjgnok/ternary_bonsai_is_a_headless_chicken/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-18 04:50"
      },
      {
       "title": "Ternary Bonsai 2 (27B) just released on Hugging Face. At <6GB in size, it can even run locally in-browser on WebGPU.",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wj6c4l/ternary_bonsai_2_27b_just_released_on_hugging/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-17 21:05"
      },
      {
       "title": "prism-ml/Ternary-Bonsai-2-27B-gguf · 351 ♥",
       "url": "https://huggingface.co/prism-ml/Ternary-Bonsai-2-27B-gguf",
       "source": "HF new models",
       "published_at": "2026-09-16 23:40"
      }
     ]
    },
    {
     "label": "Just",
     "articles": [
      {
       "title": "I just realized Courage used local LLMs to solve his problems before any of us ever did.",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wjeuy7/i_just_realized_courage_used_local_llms_to_solve/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-18 03:20"
      },
      {
       "title": "still doesn’t get what Jev is…..is it just a more generalised BERT?",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wje4xh/still_doesnt_get_what_jev_isis_it_just_a_more/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-18 02:45"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "Hacking OpenAI",
       "url": "https://www.hacktron.ai/blog/hacking-openai",
       "source": "Hacker News",
       "published_at": "2026-09-18 02:47"
      },
      {
       "title": "Installing 6 GPUs in a standard case rather than using an open-frame chassis.",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wj9u19/installing_6_gpus_in_a_standard_case_rather_than/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-17 23:28"
      },
      {
       "title": "jev reproductions tracker. keeping up with jev reproduction efforts",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wj74f4/jev_reproductions_tracker_keeping_up_with_jev/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-17 21:36"
      },
      {
       "title": "September 2026 updated chart of strix halo mini pc size chartstrix.png",
       "url": "https://www.reddit.com/r/LocalLLaMA/comments/1wj6zxt/september_2026_updated_chart_of_strix_halo_mini/",
       "source": "r/LocalLLaMA",
       "published_at": "2026-09-17 21:31"
      },
      {
       "title": "deepseek-ai/DeepSeek-V4.1-Flash · 3037 ♥",
       "url": "https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash",
       "source": "HF new models",
       "published_at": "2026-09-10 02:17"
      },
      {
       "title": "m-a-p/YuE2-3B · 737 ♥",
       "url": "https://huggingface.co/m-a-p/YuE2-3B",
       "source": "HF new models",
       "published_at": "2026-09-09 18:30"
      },
      {
       "title": "Edge0/Edge0-35B-A3B-preview · 3319 ♥",
       "url": "https://huggingface.co/Edge0/Edge0-35B-A3B-preview",
       "source": "HF new models",
       "published_at": "2026-09-08 13:56"
      },
      {
       "title": "ukisai/Swift-Qwen3.8-27b · 404 ♥",
       "url": "https://huggingface.co/ukisai/Swift-Qwen3.8-27b",
       "source": "HF new models",
       "published_at": "2026-09-08 13:35"
      }
     ]
    }
   ],
   "count": 18
  },
  {
   "key": "utoday",
   "title": "UTwente (UToday)",
   "icon": "📍",
   "note": null,
   "clusters": [
    {
     "label": "Nieuwe",
     "articles": [
      {
       "title": "VU-decaan Gregor Halff wordt nieuwe collegevoorzitter UT",
       "url": "https://news.google.com/rss/articles/CBMikwFBVV95cUxNelJaUlduTjhxNE8xZDY1TnJ6SjBORmx0RnZzd2l1SWktVUduX0RKZ2NDbG9VYVQ3MXRWTzF5T1N2SDhqRjRsY3A2bXNNY3BrZFA4cVRfTFFGeWl2eGNxTzV1ZmFaV0JnakFRY2JGTXc1OTNKNEp0RnZZZ3RlMHJydnphUHhzR005UndWbmc5Y1l4bkU?oc=5",
       "source": "UToday",
       "published_at": "2026-07-02 07:00"
      },
      {
       "title": "Nieuwe cao: lonen met 3,1 procent omhoog",
       "url": "https://news.google.com/rss/articles/CBMixgFBVV95cUxPRDJFdnFacXJ4RzBKUm5vUkFxVmZYQmpCTGgxRGlVaTNEd3lFY3BwczIxUDBjUTJQdVNOWFNwandGbWU2ZzFqYU4xUGlqSjBzeHRPbkpXVFN5clJjekFua2lvN3AtT1NzOXlMUVlaNWtUR1lEbTczS25fbVkwdnlTYlBaNDc1SmkwelRxQVVNZndUdDNXVi1KeHBVajV6bFNncGh0M2Rtd05QQUdMR1B2Y181WFNRTGt4d2JsYlJpY01fMURwNkE?oc=5",
       "source": "UToday",
       "published_at": "2026-06-24 07:00"
      },
      {
       "title": "Nieuwe hulpwijzer sociale veiligheid online",
       "url": "https://news.google.com/rss/articles/CBMiggFBVV95cUxQUks5UG5DX2FNZkFqZ0dvaWxfM3UzempKbkVKOTVELTZMX3liM24xWTdzYnRMV3JQajlTTjVlc0JuMTc0NzIyUzNqVTFXaTJvcEUzVlB4YzR5bHBmWW1RbUxaWk1vd25JeHgxWXd2QTJVRXFoWXgxLUpFR3B0LUtlNlZ3?oc=5",
       "source": "UToday",
       "published_at": "2026-05-28 07:00"
      }
     ]
    },
    {
     "label": "Grote · Bestuursfotoverkiezing",
     "articles": [
      {
       "title": "De Grote U-Today Bestuursfotoverkiezing 2026, de uitslag",
       "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxQNjU5OVlOSzctN0dKYlZ2ZVdzd2U1UWZCeEY0SXF3bzVfWTg0bXJqZGp0OGs2WUxSaGZlRVZLQjVSU2pZZGZXR1JsclBPZ1hFS1hQTVZmMXNxYTVOQ0w3NEJyS2xjZlhTWTlJQTl2LWV3bGdCaHQ2U1dLZldxeUxVVkpQYjA0LU1xY0VqMi1RU1RIM2RJVzdYdFd6UQ?oc=5",
       "source": "UToday",
       "published_at": "2026-06-25 07:00"
      },
      {
       "title": "Terug van (nooit) weggeweest: De Grote U-Today Bestuursfotoverkiezing",
       "url": "https://news.google.com/rss/articles/CBMioAFBVV95cUxNMUh5OFBxVGtqWTNXUG1kTUIxTFZSN0xwd0JWWXk4elRvdi1mZW4tYUxhU0VBOGRfQVA3bXpqaURjTUJjR1Ftb0M4QkZpQ01Mc2dZTTQzT29laXNENldKNzhOcFJ0NUtOYlNKT2dYNVYtWVRaZjU3SlAwQWs3R09TZjJaNHg5QjhuMmVPTlJjMEMzRmlXUm1Sd3luU0tGcWst?oc=5",
       "source": "UToday",
       "published_at": "2026-05-27 07:00"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "Faculteitsbestuur EEMCS: ‘Hadden eerder met elkaar het goede gesprek moeten voeren’",
       "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxOaXVxcy1ZbVNGd3l3Wjc4Wi14MFl5RDNBYW1QM0c4TjN5UE5Md2RLbUdQYVp1Vk9vVFNWVG44TzIwY2dVeWVWRDJCVVQ2MDdTSzk4eVEzTURKTTF6X21jMFdqNjVCTzZ1SE9pMkRVelBGLVlRNW1BdXBEN01GTUtDWjZ5VHpSaldSWWMyTHI0ZW0zc3o1UnVNQndzUWktY3lHVkFodDdONGV1Z3had1B3VjFuWTAxSW8?oc=5",
       "source": "UToday",
       "published_at": "2026-09-17 09:08"
      },
      {
       "title": "Arbeidsinspectie ziet drie overtredingen en tikt UT op de vingers",
       "url": "https://news.google.com/rss/articles/CBMinwFBVV95cUxOSE5LVjVZVEVuVnIwcDJVVzA5cnVVTDJsbDgwcXJvcm9xSEdLczk3bGtVTW43czRIbmZTb2JhTFJXRFJBOWM1OS10RDRSekV2QXRWRVBzZWVmcGxkUVJ1RWUxcHlpd1g4NFRCUE5mNkFNWE5YckJQelFQa1dmTVFGd1AtYnRwb0M5WUh2N0d5M3pYSWREZHdOZ05YSUlTeFk?oc=5",
       "source": "UToday",
       "published_at": "2026-09-15 14:30"
      },
      {
       "title": "Opnieuw kwestie sociale onveiligheid op UT",
       "url": "https://news.google.com/rss/articles/CBMigAFBVV95cUxPWngwSE9iNzZ1OXhFMFBCaE12X25kbFRVY2U1YWlJWlZITzJTVXRnTm5QVGE2T2FaT2Zpek5VbTFXel9rTVRiSy1SQWtPa2RXSkotR2JRXzhhSEZPejRQblRDSjBiWjBkTE96Y1Y1WGlRYmhnWk53NWJrN0x4MG1ubg?oc=5",
       "source": "UToday",
       "published_at": "2026-08-31 07:00"
      },
      {
       "title": "Elfbierentocht vs alcoholconvenant: ‘Cola mag ook’",
       "url": "https://news.google.com/rss/articles/CBMijAFBVV95cUxQRjNkNzM5VjZVV3ZEaC05UzRpVG9kLUZFQkc3Nzk3UDlqWXlPaFNzZFVieXBpbWlyTDRQcEFvNVVlRmJtX3BTTXNUZlctWGlQSzA1NXVER2NYcWJDaU1valZ1T3AxR0NsOWtHZmxpcHZvX1VJd0l5cFRqNGlSdG9mZDhEU2VyOG13bHAxZg?oc=5",
       "source": "UToday",
       "published_at": "2026-06-10 07:00"
      },
      {
       "title": "Vermoeidheid na borstkanker speelt veel vrouwen parten",
       "url": "https://news.google.com/rss/articles/CBMikAFBVV95cUxOTDE4dmZWeVI3YnllV0ZabC11VVE5ZnFnUjRhd291LUxfV1FQZ09Sb0hkdFlOZ0RkM0Z5SXVIN2NxTUx5VmdFZzR0UTRhelN3clY4TXlUQ0JEa2M2bnU4RU43TUpwc2N3T29VcEJHSldXbWVsRmhQbmlyNVBnZFh3VnNncmdoYjUzMzB6V2M2RWM?oc=5",
       "source": "UToday",
       "published_at": "2026-06-01 07:00"
      }
     ]
    }
   ],
   "count": 10
  },
  {
   "key": "morocco",
   "title": "Morocco",
   "icon": "🇲🇦",
   "note": null,
   "clusters": [
    {
     "label": "مغربية",
     "articles": [
      {
       "title": "خبرة مغربية في تدبير النفايات المشعة",
       "url": "https://www.hespress.com/%d8%ae%d8%a8%d8%b1%d8%a9-%d9%85%d8%ba%d8%b1%d8%a8%d9%8a%d8%a9-%d9%81%d9%8a-%d8%aa%d8%af%d8%a8%d9%8a%d8%b1-%d8%a7%d9%84%d9%86%d9%81%d8%a7%d9%8a%d8%a7%d8%aa-%d8%a7%d9%84%d9%85%d8%b4%d8%b9%d8%a9-1808791.html",
       "source": "Hespress",
       "published_at": "2026-09-18 05:30"
      },
      {
       "title": "دراسة مغربية ترصد ارتفاع الوزن الزائد بين الأطفال في واحات تافيلالت",
       "url": "https://www.hespress.com/%d8%af%d8%b1%d8%a7%d8%b3%d8%a9-%d9%85%d8%ba%d8%b1%d8%a8%d9%8a%d8%a9-%d8%aa%d8%b1%d8%b5%d8%af-%d8%a7%d8%b1%d8%aa%d9%81%d8%a7%d8%b9-%d8%a7%d9%84%d9%88%d8%b2%d9%86-%d8%a7%d9%84%d8%b2%d8%a7%d8%a6%d8%af-1808022.html",
       "source": "Hespress",
       "published_at": "2026-09-18 03:00"
      }
     ]
    },
    {
     "label": "المغرب",
     "articles": [
      {
       "title": "مزايدات إسبانية على الشراكة مع المغرب تصطدم بصرامة بروكسل ومدريد",
       "url": "https://www.hespress.com/%d9%85%d8%b2%d8%a7%d9%8a%d8%af%d8%a7%d8%aa-%d8%a5%d8%b3%d8%a8%d8%a7%d9%86%d9%8a%d8%a9-%d8%b9%d9%84%d9%89-%d8%a7%d9%84%d8%b4%d8%b1%d8%a7%d9%83%d8%a9-%d9%85%d8%b9-%d8%a7%d9%84%d9%85%d8%ba%d8%b1%d8%a8-1808751.html",
       "source": "Hespress",
       "published_at": "2026-09-18 05:00"
      },
      {
       "title": "المغرب يوسع دبلوماسية الأسمدة لدعم الأمن الغذائي في \"الدول الصديقة\"",
       "url": "https://www.hespress.com/%d8%a7%d9%84%d9%85%d8%ba%d8%b1%d8%a8-%d9%8a%d9%88%d8%b3%d8%b9-%d8%af%d8%a8%d9%84%d9%88%d9%85%d8%a7%d8%b3%d9%8a%d8%a9-%d8%a7%d9%84%d8%a3%d8%b3%d9%85%d8%af%d8%a9-%d9%84%d8%af%d8%b9%d9%85-%d8%a7%d9%84-1808353.html",
       "source": "Hespress",
       "published_at": "2026-09-18 02:00"
      }
     ]
    },
    {
     "label": "الانتخابية",
     "articles": [
      {
       "title": "تعدد أساليب التعبئة يطبع الأيام الأخيرة للحملة الانتخابية بمدينة العيون",
       "url": "https://www.hespress.com/%d8%aa%d8%b9%d8%af%d8%af-%d8%a3%d8%b3%d8%a7%d9%84%d9%8a%d8%a8-%d8%a7%d9%84%d8%aa%d8%b9%d8%a8%d8%a6%d8%a9-%d9%8a%d8%b7%d8%a8%d8%b9-%d8%a7%d9%84%d8%a3%d9%8a%d8%a7%d9%85-%d8%a7%d9%84%d8%a3%d8%ae%d9%8a-1809141.html",
       "source": "Hespress",
       "published_at": "2026-09-18 04:00"
      },
      {
       "title": "أوجار: المرتبة الأولى لا تصنعها الصالونات.. و\"الأحرار\" سيتصدر الانتخابات",
       "url": "https://www.hespress.com/%d8%a3%d9%88%d8%ac%d8%a7%d8%b1-%d8%a7%d9%84%d9%85%d8%b1%d8%aa%d8%a8%d8%a9-%d8%a7%d9%84%d8%a3%d9%88%d9%84%d9%89-%d9%84%d8%a7-%d8%aa%d8%b5%d9%86%d8%b9%d9%87%d8%a7-%d8%a7%d9%84%d8%b5%d8%a7%d9%84%d9%88-1809167.html",
       "source": "Hespress",
       "published_at": "2026-09-18 01:00"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "معلوف يحيي حفلا بالمسرح الملكي",
       "url": "https://www.hespress.com/%d9%85%d8%b9%d9%84%d9%88%d9%81-%d9%8a%d8%ad%d9%8a%d9%8a-%d8%ad%d9%81%d9%84%d8%a7-%d8%a8%d8%a7%d9%84%d9%85%d8%b3%d8%b1%d8%ad-%d8%a7%d9%84%d9%85%d9%84%d9%83%d9%8a-1809021.html",
       "source": "Hespress",
       "published_at": "2026-09-18 04:13"
      },
      {
       "title": "أكادير تمنع جمع وتسويق الصدفيات",
       "url": "https://www.hespress.com/%d8%a3%d9%83%d8%a7%d8%af%d9%8a%d8%b1-%d8%aa%d9%85%d9%86%d8%b9-%d8%ac%d9%85%d8%b9-%d9%88%d8%aa%d8%b3%d9%88%d9%8a%d9%82-%d8%a7%d9%84%d8%b5%d8%af%d9%81%d9%8a%d8%a7%d8%aa-1808796.html",
       "source": "Hespress",
       "published_at": "2026-09-18 03:22"
      },
      {
       "title": "تقرير يحذر فرنسا من صدمة ديمغرافية",
       "url": "https://www.hespress.com/%d8%aa%d9%82%d8%b1%d9%8a%d8%b1-%d9%8a%d8%ad%d8%b0%d8%b1-%d9%81%d8%b1%d9%86%d8%b3%d8%a7-%d9%85%d9%86-%d8%b5%d8%af%d9%85%d8%a9-%d8%af%d9%8a%d9%85%d8%ba%d8%b1%d8%a7%d9%81%d9%8a%d8%a9-1809034.html",
       "source": "Hespress",
       "published_at": "2026-09-18 02:20"
      },
      {
       "title": "معرض ياباني بالرباط يحتفي بـ\"السوشي\"",
       "url": "https://www.hespress.com/%d9%85%d8%b9%d8%b1%d8%b6-%d9%8a%d8%a7%d8%a8%d8%a7%d9%86%d9%8a-%d8%a8%d8%a7%d9%84%d8%b1%d8%a8%d8%a7%d8%b7-%d9%8a%d8%ad%d8%aa%d9%81%d9%8a-%d8%a8%d9%80%d8%a7%d9%84%d8%b3%d9%88%d8%b4%d9%8a-1809027.html",
       "source": "Hespress",
       "published_at": "2026-09-18 01:19"
      },
      {
       "title": "شابة إيرانية تنتظر الإعدام في أصفهان",
       "url": "https://www.hespress.com/%d8%b4%d8%a7%d8%a8%d8%a9-%d8%a5%d9%8a%d8%b1%d8%a7%d9%86%d9%8a%d8%a9-%d8%aa%d9%86%d8%aa%d8%b8%d8%b1-%d8%a7%d9%84%d8%a5%d8%b9%d8%af%d8%a7%d9%85-%d9%81%d9%8a-%d8%a3%d8%b5%d9%81%d9%87%d8%a7%d9%86-1808939.html",
       "source": "Hespress",
       "published_at": "2026-09-18 00:26"
      },
      {
       "title": "مؤرخون بارزون يحيون ذكرى رحيل بوشنتوف صاحب \"العالم والسلطان\"",
       "url": "https://www.hespress.com/%d9%85%d8%a4%d8%b1%d8%ae%d9%88%d9%86-%d8%a8%d8%a7%d8%b1%d8%b2%d9%88%d9%86-%d9%8a%d8%ad%d9%8a%d9%88%d9%86-%d8%b0%d9%83%d8%b1%d9%89-%d8%b1%d8%ad%d9%8a%d9%84-%d8%a8%d9%88%d8%b4%d9%86%d8%aa%d9%88%d9%81-1808979.html",
       "source": "Hespress",
       "published_at": "2026-09-18 00:00"
      },
      {
       "title": "Faux accident, vrai message : ce que cachait le live interrompu de Hicham Masrar",
       "url": "https://telquel.ma/sponsors/faux-accident-vrai-message-ce-que-cachait-le-live-interrompu-de-hicham-masrar_2008016",
       "source": "TelQuel",
       "published_at": "2026-09-17 20:00"
      },
      {
       "title": "Ahmed El Bouari: Plus de trois décennies d’expertise et d’engagement au service de l’eau et de l’agriculture",
       "url": "https://telquel.ma/sponsors/ahmed-el-bouari-plus-de-trois-decennies-dexpertise-et-dengagement-au-service-de-leau-et-de-lagriculture_2008143",
       "source": "TelQuel",
       "published_at": "2026-09-17 16:32"
      },
      {
       "title": "Pourquoi l’armée algérienne sort de sa réserve au Niger",
       "url": "https://telquel.ma/2026/09/17/pourquoi-larmee-algerienne-sort-de-sa-reserve-au-niger_2008134",
       "source": "TelQuel",
       "published_at": "2026-09-17 16:23"
      },
      {
       "title": "Code de la famille : quatre partis sur huit restent silencieux dans leurs programmes",
       "url": "https://telquel.ma/instant-t/2026/09/17/code-de-la-famille-quatre-partis-sur-huit-restent-silencieux-dans-leurs-programmes_2008123/",
       "source": "TelQuel",
       "published_at": "2026-09-17 15:58"
      },
      {
       "title": "Le Festival international du film de femmes de Salé célèbre l'héritage de Fatema Mernissi",
       "url": "https://telquel.ma/instant-t/2026/09/17/le-festival-international-du-film-de-femmes-de-sale-celebre-lheritage-de-fatema-mernissi_2008131/",
       "source": "TelQuel",
       "published_at": "2026-09-17 15:53"
      },
      {
       "title": "Nasser Bourita s’entretient à New York avec le Secrétaire général des Nations Unies",
       "url": "https://telquel.ma/instant-t/2026/09/17/nasser-bourita-sentretient-a-new-york-avec-le-secretaire-general-des-nations-unies_2008125/",
       "source": "TelQuel",
       "published_at": "2026-09-17 15:46"
      }
     ]
    }
   ],
   "count": 18
  },
  {
   "key": "netherlands",
   "title": "The Netherlands",
   "icon": "🇳🇱",
   "note": null,
   "clusters": [
    {
     "label": "Opheusden · Azc",
     "articles": [
      {
       "title": "Meerdere aanhoudingen bij protest tegen azc in Opheusden",
       "url": "https://www.telegraaf.nl/binnenland/meerdere-aanhoudingen-bij-protest-tegen-azc-in-opheusden/161624717.html",
       "source": "de Telegraaf",
       "published_at": "2026-09-17 21:50"
      },
      {
       "title": "ME grijpt in bij grimmige protesten tijdens debat over azc in Opheusden",
       "url": "https://www.nu.nl/binnenland/6410152/me-grijpt-in-bij-grimmige-protesten-tijdens-debat-over-azc-in-opheusden.html",
       "source": "NU.nl",
       "published_at": "2026-09-17 21:36"
      }
     ]
    },
    {
     "label": "Kabinet",
     "articles": [
      {
       "title": "Burgemeester Overasselt roept kabinet op om zware criminaliteit harder aan te pakken: ’Vorm van extreem geweld zichtbaar geworden’",
       "url": "https://www.telegraaf.nl/binnenland/burgemeester-overasselt-roept-kabinet-op-om-zware-criminaliteit-harder-aan-te-pakken-vorm-van-extreem-geweld-zichtbaar-geworden/161622778.html",
       "source": "de Telegraaf",
       "published_at": "2026-09-17 19:25"
      },
      {
       "title": "Grote klap voor makers van dure groene waterstof: kabinet beperkt inzet voor Nederlands energiesysteem",
       "url": "https://www.telegraaf.nl/financieel/grote-klap-voor-makers-van-dure-groene-waterstof-kabinet-beperkt-inzet-voor-nederlands-energiesysteem/161611007.html",
       "source": "de Telegraaf",
       "published_at": "2026-09-17 19:23"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "Gasprijs ruim verdrievoudigd, ook warmtenetklanten dreigen meer te gaan betalen",
       "url": "https://www.nu.nl/economie/6409827/gasprijs-ruim-verdrievoudigd-ook-warmtenetklanten-dreigen-meer-te-gaan-betalen.html",
       "source": "NU.nl",
       "published_at": "2026-09-18 03:17"
      },
      {
       "title": "Coalitie in zwaar weer: D66, VVD en CDA verdeeld over zoektocht naar steun",
       "url": "https://www.telegraaf.nl/politiek/coalitie-in-zwaar-weer-d66-vvd-en-cda-verdeeld-over-zoektocht-naar-steun/161613626.html",
       "source": "de Telegraaf",
       "published_at": "2026-09-17 19:36"
      },
      {
       "title": "LIVE | Trump zinspeelt op grote escalatie oorlog Iran: ’Met mij weet je nooit wat er kan gebeuren’",
       "url": "https://www.telegraaf.nl/buitenland/live-trump-zinspeelt-op-grote-escalatie-oorlog-iran-met-mij-weet-je-nooit-wat-er-kan-gebeuren/161563912.html",
       "source": "de Telegraaf",
       "published_at": "2026-09-17 18:02"
      },
      {
       "title": "Geen begrotingssteun vanuit oppositie na Prinsjesdag: premier Jetten terug bij af",
       "url": "https://www.nu.nl/politiek/6410108/geen-begrotingssteun-vanuit-oppositie-na-prinsjesdag-premier-jetten-terug-bij-af.html",
       "source": "NU.nl",
       "published_at": "2026-09-17 17:50"
      }
     ]
    }
   ],
   "count": 8
  },
  {
   "key": "mideast",
   "title": "Iran & Middle East",
   "icon": "🌍",
   "note": null,
   "clusters": [
    {
     "label": "Iran · War",
     "articles": [
      {
       "title": "Iran expels Swedish diplomat in retaliatory move",
       "url": "https://www.aljazeera.com/news/2026/9/18/iran-expels-swedish-diplomat-in-retaliatory-move?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-09-18 00:09"
      },
      {
       "title": "Iran war live: Trump weighs ‘big decision’ on Iran, tanker hit in Hormuz",
       "url": "https://www.aljazeera.com/news/liveblog/2026/9/18/iran-war-live-trump-weighs-big-decision-on-iran-tanker-hit-in-hormuz?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-09-18 00:00"
      },
      {
       "title": "US to allow Iran delegation to attend UN meetings in New York as war passes half-year mark",
       "url": "https://www.bbc.co.uk/news/articles/c6n8m72r13ngo?at_medium=RSS&at_campaign=rss",
       "source": "BBC World",
       "published_at": "2026-09-17 21:41"
      },
      {
       "title": "UN experts say grounds to believe US committed war crimes in Iran strikes",
       "url": "https://www.bbc.co.uk/news/articles/cm9w4n5nverdo?at_medium=RSS&at_campaign=rss",
       "source": "BBC World",
       "published_at": "2026-09-17 20:34"
      },
      {
       "title": "Iran school bombing: grounds to believe US was behind atrocity, UN finds",
       "url": "https://www.theguardian.com/world/2026/sep/17/iran-school-bombing-un-mission-us-military-behind-attack",
       "source": "Guardian World",
       "published_at": "2026-09-17 13:22"
      }
     ]
    },
    {
     "label": "Yemenis",
     "articles": [
      {
       "title": "Yemenis recount journey to Djibouti as refugee arrivals surge",
       "url": "https://www.aljazeera.com/video/newsfeed/2026/9/17/yemenis-recount-journey-to-djibouti-as-refugee-arrivals-surge?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-09-17 21:27"
      },
      {
       "title": "Verified video shows wreckage of Saudi fighter jet shot down over Yemen",
       "url": "https://www.bbc.co.uk/news/articles/c8vgy3p6k3y9o?at_medium=RSS&at_campaign=rss",
       "source": "BBC World",
       "published_at": "2026-09-17 13:47"
      },
      {
       "title": "Thursday briefing: Yemen’s war continues to threaten oil supplies– but what about its people?",
       "url": "https://www.theguardian.com/world/2026/sep/17/thursday-briefing-yemens-war-continues-to-threaten-oil-supplies-but-what-about-its-people",
       "source": "Guardian World",
       "published_at": "2026-09-17 05:45"
      }
     ]
    },
    {
     "label": "Against",
     "articles": [
      {
       "title": "UN mission alleges crimes against humanity in Iranian protest crackdown",
       "url": "https://www.aljazeera.com/video/newsfeed/2026/9/18/un-mission-alleges-crimes-against-humanity-in-iranian-protest-crackdown?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-09-18 05:26"
      },
      {
       "title": "Ireland to boycott Eurovision again over Israeli participation and ongoing Gaza deaths",
       "url": "https://www.theguardian.com/tv-and-radio/2026/sep/17/ireland-to-boycott-eurovision-again-over-ongoing-deaths-in-gaza",
       "source": "Guardian World",
       "published_at": "2026-09-17 17:32"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "US Veteran told he is ‘embarrassing’ uniform over Israeli bonds stance",
       "url": "https://www.aljazeera.com/video/newsfeed/2026/9/18/aje-onl-nf_council-removes-us-veteran-over-israel-bond-170926?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-09-18 02:44"
      },
      {
       "title": "Syria warns Israel poses ‘the greatest threat’ to Middle East stability",
       "url": "https://www.aljazeera.com/news/2026/9/18/syria-warns-israel-poses-the-greatest-threat-to-middle-east-stability?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-09-18 01:58"
      }
     ]
    }
   ],
   "count": 12
  },
  {
   "key": "ukraine",
   "title": "Ukraine War",
   "icon": "🇺🇦",
   "note": null,
   "clusters": [
    {
     "label": "Ukraine · War",
     "articles": [
      {
       "title": "Russians go to polls against backdrop of Ukraine war and Putin’s tightening grip",
       "url": "https://www.theguardian.com/world/2026/sep/18/russia-parliament-election-duma-putin",
       "source": "Guardian World",
       "published_at": "2026-09-18 02:00"
      },
      {
       "title": "Head of Ukraine's Eastern Operational Command steps down amid military reshuffle",
       "url": "https://kyivindependent.com/head-of-ukraines-eastern-operational-command-steps-down-amid-military-reshuffle/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-17 23:32"
      },
      {
       "title": "US set to approve 10 Patriot interceptors for Ukraine from Germany, records show",
       "url": "https://kyivindependent.com/us-set-to-approve-10-patriot-interceptors-for-ukraine-from-germany-records-show/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-17 21:38"
      },
      {
       "title": "Zelensky, von der Leyen plan to meet at UN as EU releases $3.7 billion for Ukraine",
       "url": "https://kyivindependent.com/zelensky-von-der-leyen-plan-to-meet-at-un-as-eu-releases-3-7-billion-for-ukraine/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-17 20:26"
      },
      {
       "title": "Ukraine war latest: Russian missile, drone attack on Kyiv injures at least 20",
       "url": "https://kyivindependent.com/ukraine-war-latest-russian-missile-drone-attack-on-kyiv-injures-at-least-20/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-17 18:05"
      }
     ]
    },
    {
     "label": "Russian",
     "articles": [
      {
       "title": "Fire engulfs Zaporizhzhia shopping centre after Russian strike",
       "url": "https://www.aljazeera.com/video/newsfeed/2026/9/18/fire-engulfs-zaporizhzhia-shopping-centre-after-russian-strike?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-09-18 05:03"
      },
      {
       "title": "'I'm Russian, and I support my country,' Ovechkin says after appearing in campaign ad for Putin's party",
       "url": "https://kyivindependent.com/im-russian-and-i-support-my-country-ovechkin-says-after-appearing-in-campaign-ad-for-putins-party/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-18 01:56"
      },
      {
       "title": "The situation in Russian-occupied Oleshky was dire. Now it's 'hell'",
       "url": "https://kyivindependent.com/the-situation-in-russian-occupied-oleshky-was-dire-now-its-hell/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-17 18:47"
      }
     ]
    },
    {
     "label": "Russia",
     "articles": [
      {
       "title": "Putin confiscates Nestle, Auchan assets in Russia",
       "url": "https://kyivindependent.com/putin-confiscates-nestle-auchan-assets-in-russia/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-18 04:53"
      },
      {
       "title": "Russia election: Could other parties challenge United Russia?",
       "url": "https://www.aljazeera.com/video/newsfeed/2026/9/17/aje-onl-nf_medvedenkod-parties_challenge_united_russia-170926?traffic_source=rss",
       "source": "Al Jazeera",
       "published_at": "2026-09-17 22:19"
      },
      {
       "title": "Trump plans to sign Russia sanctions bill 'soon,' White House source says",
       "url": "https://kyivindependent.com/trump-plans-to-sign-russia-sanctions-bill-soon-white-house-source-says/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-17 16:35"
      }
     ]
    },
    {
     "label": "More headlines",
     "articles": [
      {
       "title": "Poll tracks Zelensky's trust rating amid corruption investigation",
       "url": "https://kyivindependent.com/poll-tracks-zelenskys-trust-rating-amid-corruption-investigation/",
       "source": "Kyiv Independent",
       "published_at": "2026-09-17 18:52"
      }
     ]
    }
   ],
   "count": 12
  }
 ]
};
