"""Generate data.json for the static news site.

Fetches the feeds (news_client), builds each country's briefing (summarizer)
and writes data.json next to this script. Designed to run on a schedule in
GitHub Actions, but works identically on your machine.

Behavior notes:
- If the country payload is unchanged (ignoring the volatile date/time fields)
  the file is left untouched and we exit 0 — the workflow then skips the
  commit, so the repo only gains a commit when the news actually changed.
- If every feed for every country fails we exit non-zero WITHOUT writing, so
  the last good data.json stays published (stale beats broken).
"""

import json
import sys
import time
from pathlib import Path

from news_client import NewsFetchError, fetch_all_news
from summarizer import briefing_for

DATA_PATH = Path(__file__).resolve().parent / "data.json"
# A JS mirror of data.json. Pages uses fetch() for live refresh, but browsers
# block fetch() on file:// pages, so double-clicking index.html would show an
# empty page. A <script src="data.js"> still loads on file://, so we also emit
# the payload as a plain assignment and the page falls back to it offline.
DATA_JS_PATH = Path(__file__).resolve().parent / "data.js"

# Volatile fields excluded when deciding whether anything actually changed.
_VOLATILE = ("date", "generated_at")


def build_payload() -> dict:
    """Full site payload. Raises NewsFetchError if nothing could be fetched."""
    countries = fetch_all_news()
    for country in countries:
        country.briefing = briefing_for(country.articles)

    now = time.localtime()
    return {
        "date": (
            f"{time.strftime('%A', now)} {now.tm_mday} "
            f"{time.strftime('%B', now)} {now.tm_year}"
        ),
        "generated_at": time.strftime("%H:%M UTC", time.gmtime()),
        "error": None,
        "total_stories": sum(len(c.articles) for c in countries),
        "countries": [
            {
                "code": c.code,
                "name": c.name,
                "flag": c.flag,
                "briefing": c.briefing,
                "articles": [
                    {
                        "title": a.title,
                        "url": a.url,
                        "source": a.source,
                        "published_at": a.published_at,
                    }
                    for a in c.articles
                ],
            }
            for c in countries
        ],
    }


def core(payload: dict) -> dict:
    return {k: v for k, v in payload.items() if k not in _VOLATILE}


def main() -> int:
    try:
        payload = build_payload()
    except NewsFetchError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if DATA_PATH.exists() and DATA_JS_PATH.exists():
        try:
            previous = json.loads(DATA_PATH.read_text(encoding="utf-8"))
            if core(previous) == core(payload):
                print("data.json unchanged — skipping write")
                return 0
        except (OSError, json.JSONDecodeError):
            pass  # unreadable/absent: just write fresh

    serialized = json.dumps(payload, ensure_ascii=False, indent=1)
    DATA_PATH.write_text(serialized + "\n", encoding="utf-8")
    # JSON is valid JS object-literal syntax, so we wrap the same bytes as an
    # assignment. U+2028/U+2029 are legal in JSON strings but were historically
    # illegal in JS string literals, so we escape them to keep both files safe.
    js = serialized.replace(" ", "\u2028").replace(" ", "\u2029")
    DATA_JS_PATH.write_text(
        "// Generated by generate_data.py — do not edit; see data.json.\n"
        "window.__NEWS__ = " + js + ";\n",
        encoding="utf-8",
    )
    print(f"wrote data.json + data.js: {payload['total_stories']} stories")
    return 0


if __name__ == "__main__":
    sys.exit(main())
